---
- name: Disable default Redis module
  ansible.builtin.command: dnf module disable redis -y

- name: Enable Redis 7 module
  ansible.builtin.command: dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.package:
    name: redis
    state: present

- name: Replace bind IP in redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: restart redis

- name: Disable protected mode in Redis
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode\s+yes'
    line: 'protected-mode no'
  notify: restart redis

- name: Enable and start Redis service
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes
