---
- name: Disable Nginx module
  ansible.builtin.command: dnf module disable nginx -y

- name: Enable Nginx 1.24 module
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Remove default content
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Download frontend zip
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: Extract frontend zip into /usr/share/nginx/html
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy custom nginx configuration
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
