---
- name: Install MySQL server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Start and enable MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Set MySQL root password (non-interactive)
  ansible.builtin.command: >
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1'; FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash
