---
- name: Disable default Node.js module
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable Node.js 20 module
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install Node.js
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Create roboshop system user
  ansible.builtin.user:
    name: roboshop
    system: yes
    home: /app
    shell: /sbin/nologin
    comment: "roboshop system user"

- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download catalogue.zip file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: Extract catalogue.zip into /app
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install Node.js dependencies in /app
  ansible.builtin.npm:
    path: /app

- name: Copy catalogue service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
  notify: restart catalogue

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Copy mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Shell
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: Check if master data already exists
  ansible.builtin.shell: |
    mongosh --host mongodb.daws-84job.sbs --quiet --eval 'db.products.countDocuments()'
  register: product_count

- name: Debug count (optional)
  ansible.builtin.debug:
    msg: "Products count: {{ product_count.stdout }}"

- name: Load products
  ansible.builtin.shell: mongosh --host mongodb.daws-84job.sbs < /app/db/master-data.js
  when: product_count.stdout | int == 0
